### ISSUE TITLE
Feature request: Custom function to stop reading excel file

### ISSUE THREAD

**Issue by piyapan039285** [NorakGithub/django-excel-tools#3]
# Description
Sometimes `worksheet.calculate_dimension()` returns very large number of rows. So, I think it would be better if I can set function which tell the API when to stop reading excel file.

# Purpose solution
For example, I can set function which will stop read excel if first column is empty.
```
class MySerializer(ExcelSerializer):

     def should_stop_reading(row_number, row_data):
          return row_data[0] is None
```

**Comment by NorakGithub** [comment]
This has been fix in this PR #17
